/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package eStoreSearch;

public class App {

    public static void main(String[] args) {
        GUI gui = new GUI();
        gui.setVisible(true);
    }
}
